name: Daily Task Dispatcher

on:
  schedule:
    - cron: '0 17 * * *'  # UTC时间17:00=北京时间1:00（次日）
    - cron: '*/5 * * * *'  # 测试用：每5分钟触发一次（调试后删除）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install gspread google-auth requests

      - name: Create service account file
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > service_account.json
          # 简单验证文件是否创建成功
          ls -la service_account.json

      - name: Run task script
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python main.py
