name: Daily Task Dispatcher

on:
  schedule:
    - cron: "22 13 * * *"  # 每天北京时间 21:22（测试时用）
  workflow_dispatch:       # 允许你手动运行

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create service_account.json
        run: |
          printf '%s' "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Run the task dispatcher
        run: python main.py
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
